FROM nginx

COPY ./dockerbits/openmoney-network/om.nginx.conf /etc/nginx/conf.d/default.conf
COPY ./openmoney-network/index.html /usr/share/nginx/html/index.html
COPY ./openmoney-network/public /usr/share/nginx/html/public
